
[[constraint]]
  branch = "master"
  name = "github.com/cbroglie/mustache"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/gregjones/httpcache"
