[[constraint]]
  branch = "master"
  name = "github.com/Unknwon/goconfig"

[[constraint]]
  name = "github.com/cbroglie/mustache"
  version = "1.0.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/static"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/gregjones/httpcache"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/newrelic/go-agent"
  version = "1.11.0"
